[package]
name = "rust-pass"
version = "0.1.0"
edition = "2021"

[dependencies]
arboard = "=3.4.1"
clap = { version = "4.5.17", features = ["derive"] }
rand = "0.8.4"
aes = "0.7"
block-modes = "0.8"
pbkdf2 = "0.9"
hmac = "0.12"
sha2 = "0.10"
rusqlite = "0.32.1"
